#!/bin/bash

find . -type f -name "*.gif" -print \
  | while read file; do
      filename="${file##*/}"          # remove path
      echo "${filename%.gif}"        # remove .gif extension
    done \
  | sort -f